import { chromium } from 'playwright-core';

const browser = await chromium.launch({ executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', headless: true });
const context = await browser.newContext({ viewport: { width: 1280, height: 900 }, locale: 'vi-VN' });
const page = await context.newPage();
await page.goto('http://127.0.0.1:5173/dat-ghe/s1', { waitUntil: 'networkidle' });
await page.getByRole('button', { name: /Ghế A1,/ }).click();
await page.getByRole('button', { name: /Ghế A2,/ }).click();
await page.getByRole('button', { name: /Giữ ghế & tiếp tục/ }).click();
await page.getByRole('heading', { name: /Xác nhận trước khi đèn tắt/ }).waitFor();
if (await page.getByRole('button', { name: /Xác nhận mô phỏng/ }).isEnabled()) throw new Error('Payment action must require demo consent');
await page.getByRole('checkbox', { name: /Tôi hiểu đây là thao tác mô phỏng/ }).check();
await page.getByRole('button', { name: /Xác nhận mô phỏng/ }).click();
await page.getByRole('heading', { name: 'Vé đã sẵn sàng.' }).waitFor();
const tickets = await page.locator('.cinema-ticket').count();
if (tickets !== 2) throw new Error(`Expected 2 tickets, received ${tickets}`);
const qrCodes = await page.locator('.ticket-qr').count();
if (qrCodes !== 2) throw new Error(`Expected 2 QR codes, received ${qrCodes}`);
const qrLoaded = await page.locator('.ticket-qr').evaluateAll((images) => images.every((image) => image instanceof HTMLImageElement && image.complete && image.naturalWidth > 0 && image.src.startsWith('data:image/gif;base64,')));
if (!qrLoaded) throw new Error('Ticket QR images failed to render');
const startsAtTop = await page.evaluate(() => window.scrollY === 0 && document.activeElement?.id === 'main-content');
if (!startsAtTop) throw new Error('Ticket navigation did not reset scroll and focus to content');
await page.screenshot({ path: '../.impeccable/review/ticket-desktop.png', fullPage: true });
await page.setViewportSize({ width: 390, height: 844 });
const fitsMobile = await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth);
if (!fitsMobile) throw new Error('Ticket page overflows the 390px viewport');
await page.screenshot({ path: '../.impeccable/review/ticket-mobile.png', fullPage: true });
console.log('E2E_SMOKE_OK: 2 seats -> hold -> simulated payment -> 2 tickets');
await context.close();
await browser.close();
